### PR TITLE
9872 task ui

### PR DESCRIPTION
**Pull request by DevneyHamilton**

### CODE REVIEW

**Comment by DevneyHamilton** [comment]
Task UI screenshot:
Screen Shot 2019-07-23 at 9 44 54 AM

Showing pagination:
Screen Shot 2019-07-23 at 9 44 31 AM

**Comment by emitche** [comment]
image

The title of the page does not appear to be working properly.

**Review by emitche — COMMENTED** [review]
The UI looks like it's working as expected except for the item I added.

**Comment by DevneyHamilton** [comment]
> image
> 
> The title of the page does not appear to be working properly.

Thank you @emitche for testing. I am not able to reproduce this. I re-pulled this branch, restarted the server, but I see 'Tasks' as the title. If you have a chance later or on Friday morning to screenshare, that would be helpful.

**Comment by DevneyHamilton** [comment]
Update on the title translation: git registered a change that deleted whitespace in the translation file, so I committed it. I have no idea if it's related to the translation not coming through or not (since it's been coming through on both versions for me), but there is that change in here now.

**Comment by emitche** [comment]
I just restarted the server and that fixed it. The translation was clearly in the right place in the files, so that was strange. Thank you, @DevneyHamilton.

**Comment by DevneyHamilton** [comment]
> I just restarted the server and that fixed it. The translation was clearly in the right place in the files, so that was strange. Thank you, @DevneyHamilton.

Awesome - thanks so much for catching it @emitche!!

**Review by meltheadorable — APPROVED** [review]
Looks great!

**Pull request merged**
