### PR TITLE
10298 duplicate step modal

### PR DESCRIPTION
**Pull request by emitche**
- Adjust duplicate step modal styling

### CODE REVIEW

**Comment by emitche** [comment]
Updated duplicate step modal:

image

**Comment by emitche** [comment]
Current duplicate step modal:

image

**Review by meltheadorable — APPROVED** [review]

**Comment by emitche** [comment]
It is possible for one of the inputs to cause a line that should be one line to break to two lines:

image

**Comment by emitche** [comment]
Related bug: If "Repeat" "End" option is selected, but not filled out, the form can be submitted. The step will not duplicate, as is the correct action.

image

**Pull request merged**
