### PR TITLE
10193: update accounting setup instructions to reflect changes in int…

### PR DESCRIPTION
**Pull request by DevneyHamilton**
…uit and madeline UIs

### CODE REVIEW

**Comment by DevneyHamilton** [comment]
@emitche I reset my local db (according to accounting setup instructions, and tested with Sandbox Company 1 under the madelineqb@sassafras.coop Intuit Developer account

I was able to
- connect to the sandbox company
- create transactions for a loan that was created in the sample data
- edit a transaction in qb and get the changes back when refreshing Transactions page for the loan
- manually run the Update All Loans Task. This reported a success, and no errors in the sidekiq log. It has a 'message' reporting errors, but that's a bug that I can fix in 10191. 

Should I work on a more elaborate set up for testing accounting on local? Right now, we have to recreate any accounting data manually when we reset the db. If the sandbox co already has loans txns, they will only come through to Madeline local if the loan transactions in qb happen to match (by loan ID, I'm pretty sure) loans in the reset db.

**Comment by emitche** [comment]
@DevneyHamilton Sorry I am just seeing this. I will take a look.

**Comment by emitche** [comment]
@DevneyHamilton From what you have described here, this sounds good. I will be sending you a Slack thread with things I encountered when trying to test a couple of weeks ago. Thank you so much!

**Review by emitche — COMMENTED** [review]
Changes look good here.

**Pull request merged**
