### PR TITLE
10563 accounting settings ux tweaks

### PR DESCRIPTION
**Pull request by emitche**
- Style Accounting Settings page to take into account multiple settings inside form

### CODE REVIEW

**Comment by emitche** [comment]
(I'm using fake data and a sandbox right now, so please don't be alarmed by my settings. 🙂 )

@DevneyHamilton I added some context about read-only, as well as cleaned up the form so the form is clearer.

image

image

**Review by DevneyHamilton — APPROVED** [review]
This is SO fantastic!! Thank you so much!

**Comment by DevneyHamilton** [comment]
Re QA: I pulled the branch to see the changes, and they worked for me. So that might cover QA?

**Comment by emitche** [comment]
> Re QA: I pulled the branch to see the changes, and they worked for me. So that might cover QA?

Sounds good. Thank you! It's all styling changes only.

**Pull request merged**
