### PR TITLE
7719 rich text on logs

### PR DESCRIPTION
**Pull request by emitche**
- Add rich text formatting to logs
- Rich text added to details, additional notes, and private notes
- Log summary remains an input type text box
- Display log summary as plain text
- Display details, additional notes, and private notes as html

### CODE REVIEW

**Comment by emitche** [comment]
I'll have @meltheadorable do code review.

@DevneyHamilton would you be available for a QA review of this after the code review comes back? I can add images and a flow of changes, so you know what changed. Thanks a bunch!

**Review by meltheadorable — APPROVED** [review]
😸

**Comment by DevneyHamilton** [comment]
QA notes: 

Able to add bold, italic, underlined, link, photo, video, table to details, additional notes, and private notes:
Screen Shot 2019-06-25 at 2 06 20 PM
Screen Shot 2019-06-25 at 2 06 15 PM
Screen Shot 2019-06-25 at 2 06 09 PM

One potential small issue - when there's an error saving, I get html and I can't see the rich text editor icons: Screen Shot 2019-06-25 at 2 05 41 PM


. . . .this shouldn't block any usage though, because if I can save, then I can edit. I do see the rich text editor icons when I edit a saved log. 
Screen Shot 2019-06-25 at 2 08 54 PM

**Comment by emitche** [comment]
@DevneyHamilton Thanks for the QA review and for catching that bug.

**Comment by emitche** [comment]
There is a related bug introduced with this code that can be addressed in this sprint or in the next sprint.

**Pull request merged**
