### PR TITLE
10505: create problem loan txn entry if transaction extractor cannot …

### PR DESCRIPTION
**Pull request by DevneyHamilton**
…process account in qb data

This addresses the "undefined method `[]' for nil:NilClass" errors from the transaction extractor in the line `    acct = Accounting::Account.find_by(qb_id: li[qb_li_detail_key]['account_ref']['value'])`. Spot checking loans with this error showed that all spot checked had a line item with a 0.00 amount and no other fields (including no account set). These are all manually created qb txns. Madeline should not handle those line items, and admins should fix them in qb. This PR creates a ProblemLoanTransaction entry instructing the admin to check the transaction in qb and fix it.

### CODE REVIEW

**Comment by DevneyHamilton** [comment]
Individual loan view of problem loan transactions:
Screen Shot 2020-03-10 at 2 04 16 PM

All-loans view of problem loan transactions
Screen Shot 2020-03-10 at 2 04 02 PM

**Comment by DevneyHamilton** [comment]
For QA: in quickbooks on sandbox (or with a test loan in staging, with the Madeline STaging Company NEW), in quickbooks, add a line item to an existing transaction where the line item just has an amount 0.00. Update the loan in Madeline. Go to /admin/accounting/problem_loan_transactions. This loan should have an entry. click the entry and see if it displays like the screenshots above.

**Review by emitche — APPROVED** [review]
This code looks good to me.

**Comment by emitche** [comment]
@meltheadorable Approved the code.

**Comment by emitche** [comment]
QA result: Beautiful update. Thank you!

**Pull request merged**
