### PR TITLE
9667 log modal

### PR DESCRIPTION
**Pull request by emitche**
- Refactor modals to ask for specific user input before being closed
- Remove x and backdrop closing of modals for modals that might close user edits by mistake
- Use buttons with text for closing modals that may have had user edits

### CODE REVIEW

**Review by meltheadorable — APPROVED** [review]

**Comment by DevneyHamilton** [comment]
QA notes:
Timeline step edit modal only closes with 'cancel' link at top, cancel button, or submit button. 
Add log modal only closes with Cancel or Save Log.
Add/edit question or group modal only closes with Cancel or Save
Add media modal only closes with Cancel or Submit
Duplicate Step modal only closes with Cancel or Duplicate
Add step only closes with Cancel or Submit

QA questions:
how to test for a required log? 
any other modals?

**Comment by emitche** [comment]
> QA questions:
> how to test for a required log?
> any other modals?

### Required Log Modal/ Timeline Step Move Modal
Inside a timeline for a loan, find a step that has been finalized and is locked. An example of a finalized and locked step can be seen at https://ms-staging.theworkingworld.org/admin/loans/2860/timeline. The non-italic items are finalized.

Click on the step. The modal will open. See Finalized in the modal to see if the item is Finalized and Locked.

image

Edit the scheduled start date or duration. When you do this, a log will be required to be entered.

In terms of QA, it helps to check that the user must enter that log, that they can't exit out of the process by clicking outside the modal or clicking on the x.

### Media modal
The media modal can be opened by visiting a loans details page. At the bottom, add media by clicking the big + sign. See the bottom of https://ms-staging.theworkingworld.org/admin/loans/2860/details for an example of loan media.
image

## Other modals
For documentation later.

### Project step
Project step modal can be opened by clicking on a step in the timeline or from the calendar. Or you can add a new step. 

Timeline example:
image

Add step and add group buttons:
image

### Project group
Project group modal can be accessed by adding a group or clicking on a group inside the timeline.

Example of a group. Clicking on the gear or the block will open the group modal:
image

### Duplicate step modal

From the timeline, click on the gear inside a project step and select Duplicate.

image

**Comment by emitche** [comment]
@DevneyHamilton I added some details about testing the modals. If you have any questions, let me know. Thank you!

**Comment by emitche** [comment]
It would likely be good to pull this information into a manual testing document for future reference. I'll keep this in mind for the future.

**Comment by DevneyHamilton** [comment]
Tested required log modal; only way to close is 'Add Log."
Note: I have to edit the duration to get the prompt to add a required log. Editing the start date did not prompt me to add a required log.

**Comment by DevneyHamilton** [comment]
@emitche the how-to notes are amazing and we should definitely keep them for future testing!!

**Comment by emitche** [comment]
> Note: I have to edit the duration to get the prompt to add a required log. Editing the start date did not prompt me to add a required log.

I'll make a note of this. I'm not sure what prompts required logs related to the start date. This helps. Thank you.

**Pull request merged**
