### PR TITLE
10280: get rid of error when je assigned type 'other' so clearing and…

### PR DESCRIPTION
**Pull request by DevneyHamilton**
… opening txns show up correctly

### CODE REVIEW

**Comment by DevneyHamilton** [comment]
Clearing txns show up as 'other'
Screen Shot 2019-11-26 at 4 25 36 PM

Interest opening txn shows up as 'other' (principal opening shows as 'Disbursement')
Screen Shot 2019-11-26 at 4 30 41 PM

**Review by meltheadorable — APPROVED** [review]

**Comment by DevneyHamilton** [comment]
for QA: Since this is for handling manually created transactions (instructions for TWW staff are here: https://docs.google.com/document/d/1rkv-5MJVckKeY8c9cGI5nlPDw7427d4G_jHgQSIDBs4/edit) in quickbooks, it could be a pretty involved qa process. But staging currently has two loans with these types of txns - https://ms-staging.theworkingworld.org/admin/loans/3015/transactions and https://ms-staging.theworkingworld.org/admin/loans/3016/transactions. If after deploy, those show type "other" in place of  "missing option label - value: other" and no longer have the warning about broken transactions at the top, then 10280 is working.

**Comment by DevneyHamilton** [comment]
Additional note: after this is deployed, the ending interest, principal, and total balances on loan 3015 on staging should still be $0. (they are currently $0).

**Comment by emitche** [comment]
Will QA this on staging.

**Pull request merged**
